### ISSUE TITLE
Allow for string only entries in actions and parts

### ISSUE THREAD

**Issue by gsong** [gsong/interdiagram#4]
Allow for string entries, instead of strictly enforcing dicts, in `parts` and `actions`, so instead of:

```yaml
Experience Card:
  parts:
    - Part 1:
    - Part 2: Part 2
```

You can just write:

```yaml
Experience Card:
  parts:
    - Part 1
    - Part 2: Part 2
```
